global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'graduate'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['graduate:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']